'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TextTwist2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1486485571_198high_loud_music_on_sound_speaker_volume_81180() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1486485571-198high-loud-music-on-sound-speaker-volume_81180", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _81Y2lHoTFqL_transformed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("81Y2lHoTFqL-transformed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _81Y2lHoTFqL_transformed_transformed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("81Y2lHoTFqL-transformed-transformed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property candado() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("candado", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cristian,1234
        '''Asiermmg,1234
        '''ElenaLuz,P@ssw0rd
        '''Javi123,5ecr3t!
        '''Maria23_,H0laMund0
        '''Pablo00,C0ntr@s3n1@
        '''Lucia33,Qwerty12
        '''DavidMtz,Myp@ssw0rd
        '''Silvia20,7h3s3cr3t
        '''Carlos87,N0t3asy
        '''Laura1_,@bcd1234
        '''Alex0_,P@s5word.
        '''</summary>
        Friend ReadOnly Property credenciales() As String
            Get
                Return ResourceManager.GetString("credenciales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property interrogante() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("interrogante", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MainGame() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MainGame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.IO.UnmanagedMemoryStream similar a System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property MainMenu() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("MainMenu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a camote,Tubérculo comestible de América Central y México.
        '''cometa,Cuerpo celeste compuesto de hielo y polvo que describe una órbita elíptica alrededor del Sol.
        '''acote,Conjunto de ramas de la vid, después de cortar los racimos.
        '''cateo,Examen o inspección minuciosa que se hace para buscar algo.
        '''mateo,Nombre propio de varón.
        '''meato,Cada una de las aberturas u orificios naturales de algunos animales.
        '''acto,Acción que realiza una persona.
        '''ateo,Que niega la existencia de Dios o deidades.
        '''cate,Verbo que signific [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property palabras() As String
            Get
                Return ResourceManager.GetString("palabras", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
